---
title: 'TibetanAntelope_Microbiome_MaAsLin2'
author: "Yue Shi, University of Washington"
date: "r date()"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: 4
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

### Get it ready

Load the libraries
```{r}
library(tidyverse) #THE package for data manipulation
library(skimr)
library(vegan)
library(Maaslin2)
```

Read the data
```{r}
rm(list=ls())
count <- read.table("./CM_output/ASV_count_filter_rmSession.txt",header=TRUE, row.names=1) 
tax <- read.table("./CM_output/ASV_taxonomy_filter_rmSession.txt", header=TRUE, row.names=1)
meta <- read.csv("./CM_output/meta_filter.csv", header=T) 

# make sure the order is the same
identical(rownames(count), rownames(tax))
identical(colnames(count), meta$sampleID)

tax=as.matrix(tax)

# log transform hormone data
meta <- meta %>% 
  mutate(T3=log(T3)) %>% 
  mutate(cortisol=log(cortisol))
```

### Agglomerate to genus level
```{r}
rownames(meta) <- meta$sampleID
ps <- phyloseq(otu_table(count,taxa_are_rows=T), 
               sample_data(meta),
               tax_table(tax))

GenusFiltered <- subset_taxa(ps, Genus != "NA")
ps.genus = tax_glom(GenusFiltered, "Genus") #merge ASV with the same taxonomy, summing the abundance
ps.genus

cts.genus <- otu_table(ps.genus) %>% 
  as.data.frame()
```

### Multivariate general linear mixed model

GLMM (generalized linear mixed model) is an extension of generalized linear model to include both fixed and random effects.To run MaAsLin2, you will need count file, and meta file. Samples not included in both files will be removed from the analysis.

```{r}
fit<- Maaslin2(
  input_data=t(cts.genus),
  input_metadata = meta,
  output="./data/",
  min_abundance = 0.001, #minimum relative abundance for each feature;
  min_prevalence = 0.1, # ASV needs to be observed in at least % samples, 
  max_significance = 0.05, #q value threshold for significance
  fixed_effects = c("reproduction", "T3", "cortisol"), #for categorical variable, MaAsLin2 treat the first category in alphabetical order as the reference. So here the reference is Late pregnancy.
  random_effects = c("session"),
  normalization="TSS",
  transform="AST",
  analysis_method="LM",
  correction="BH",
  standardize = TRUE #standardize continuous variable;
)


taxa <- tax %>% 
  as.data.frame() %>% 
  rownames_to_column("id")

out<- fit$results %>% 
  filter(qval<0.05)

out_taxa <- left_join(out, taxa, by=c("feature"="id"))

write.table(out_taxa, "./data/MaAsLin2_sig_tax.txt", quote=F, row.names = F)
```



